### PR TITLE
Adds support for multiple TYPE parameters

### LINKED ISSUE #343: vCard: Parse multiple types
> These type parameter values can be specified as a parameter list (e.g., TYPE=text;TYPE=voice) or as a value list (e.g., TYPE="text,voice").

https://tools.ietf.org/html/rfc6350#section-6.4.1

### Expected behaviour
```
TEL;VALUE=uri;TYPE=work;TYPE=voice:tel:+33-89-01-23-45
```
should be parsed to:
```json
[ "tel", { "type": ["work", "voice"] }, "uri", "tel:+33-89-01-23-45" ],
```
### Actual behaviour
The param value is set to the last occurring value:
```json
[ "tel", { "type": "voice" }, "uri", "tel:+33-89-01-23-45" ],
```

-------

I modified a vcard parser test to display the issue:
https://github.com/Henni/ical.js/commit/6d4365e374a12a20d4433f6f6a4186baafa126c3

### PR DESCRIPTION
**Pull request by caugner**
Fixes #343.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by caugner** [comment]
@kewisch Should I resolve the conflicts (by rebuilding) or will you do this anyway before merging?

PS: Maybe this could be automatised via Travis.

**Comment by giddyhup** [comment]
I made this issue my start page. How many trees may I plant to get the fix implemented?

**Comment by Nemental** [comment]
@giddyhup I feel you! :D

**Comment by giddyhup** [comment]
@kewisch please include this!

**Comment by kewisch** [comment]
This looks good, thanks so much! I've added another test for iCalendar. I'm not sure if it is technically allowed to have multiple parameters there, but at least we'd be able to read them.

**Comment by kewisch** [comment]
> I made this issue my start page. How many trees may I plant to get the fix implemented?

I hope you planted a lot of trees. If so, not getting around to this may have been my easiest contribution to save the planet yet ;-)

**Comment by giddyhup** [comment]
grafik

https://teamtrees.org/#recent-donations
@kewisch

**Comment by caugner** [comment]
@kewisch 

> I'm not sure if it is technically allowed to have multiple parameters there

Thanks for merging. Indeed it is allowed:

grafik

Source: https://tools.ietf.org/html/rfc6350#section-6.4.1

**Pull request merged**
