### PR TITLE
Fix for..in loop with modified prototype

### PR DESCRIPTION
**Pull request by amrod-**
Code in for..in loops break when ical.js is used in combination with code that adds functions to the prototype of Arrays. A simple hasOwnProperty check in the loops solves that this.

### CODE REVIEW

**Comment by kewisch** [comment]
Interesting, which Libraries are causing this? Ideally, those libraries should be using `Object.defineProperty` to make those functions non-enumerable properties.

For short loops with just 2-3 lines its ok, but for long loops I'd prefer using `continue` to skip the loop if its not an own property. This also avoids the extra indentation level. Do you think you could change that?

**Comment by amrod-** [comment]
I'm using emberjs, having them non-enumerable would indeed be the preferred option.

The code is changed to use <code>continue</code> in long loops, if more needs to be changed just let me know.

**Comment by kewisch** [comment]
Looks good now, thanks for the patch! I hope ember fixes their prototypes in the future.

**Comment by amrod-** [comment]
Thanks for merging.

**Pull request merged**
