### PR TITLE
Convert all to v2 (WIP) feedback=kewisch

### PR DESCRIPTION
**Pull request by lightsofapollo**
This converts everything over to v2 and removes all code that is not actively used.
Also fixes a bug in Recur#toString and updates the validator.

I am making this as "WIP" because I have not yet conduced the manual testing to consider this 100% stable, I am going to switch gaia over to this new version of the library and fix any issues that arise.

I renamed the old parser (which we still use parts of) to "decoration_parser" and it handles a few special types.

I will post results here.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
Another note: we added about 300 lines of code (sloc) during this rewrite, I think most of it duplication between the new and old parser. I want to carefully optimize the remaining types later on which should also reduce the duplication.

**Comment by lightsofapollo** [comment]
@kewisch I found a few minor bugs and fixed them this should be ready for full review now.

**Comment by kewisch** [comment]
Could you clarify what you mean with "removes all code that is not actively used" ? If this removes any API methods that were in there before, I'd appreciate a list. The original methods I implemented were all the ones I needed for using this in Lightning.

**Comment by kewisch** [comment]
Afterwards, feel free to push the merge button :)

**Comment by lightsofapollo** [comment]
@kewisch Let me come up with a list, the majority of all methods are very similar if not the same. 
Some methods where removed (like countParameters) others where added (removeAllComponents).

The biggest change is to how values are handled as we don't use value objects for undecorated (float, string, int, boolean) types.

I did not arbitrarily remove anything but some things where restructured around use with jCal.

(I was specifically referring to removing "v2" from everything and removing the original classes/files.)

**Comment by lightsofapollo** [comment]
# Change summary

## Component

removed: undecorate (use toJSON/.jCal to get jCal)
removed: clearAllProperties removed in favor of -> removeAllProperties (same method signature as removeAllComponents)

## Property

removed: undecorate (use toJSON/.jCal)
removed: setStringValue (setValue with a string works the same way but also handles decorated objects)
removed: getValueType -> use .type
renamed: getParameterValue -> getParameter
removed: getParameterType
removed: countParameters

---

Misc changes:

removed serializer.js in favor of stringify.js.
You can do stuff like `ICAL.stringify.component(ICAL.Component)`

**Comment by lightsofapollo** [comment]
@kewisch Per your comment, landing. As always we have git history if something is missing.

I will make a separate PR to update the missing parser changes (period/utc-offset).
Also- I have some changes to make to the recur parser I am fairly sure it leaks memory somehow...

**Pull request merged**
