### PR TITLE
Fixes the parsing of single-value parameters following a multi-value parameter

### LINKED ISSUE #386: Parser splits vCard ADR parameter "LABEL" at comma despite quoting (when it appears after multi-value parameter "TYPE")
While investigating [an issue](https://github.com/nextcloud/contacts/issues/1009), I noticed that the ical.js parser seems to split values that contain a comma, even if the value is quoted or the comma escaped.

This causes `ICAL.stringify.component` to fail on the parsed jCal object.

**Update**: I had a look [at the `ADR` section](https://tools.ietf.org/html/rfc6350#section-6.3.1) in the RFC 6350:

> Where it makes semantic sense, individual text components can include multiple text values (e.g., a "street" component with multiple lines) separated by the COMMA character (U+002C).

This makes me think that actually the text parsing itself is correct, but rather `ICAL.stringify.property` should convert the Array back into a `string` [at this location](https://github.com/mozilla-comm/ical.js/blob/v1.3.0/lib/ical/stringify.js#L126-L128), rather than calling `ICAL.stringify._rfc6868Unescape(value)` with `value` being an `Array` (that doesn't have the `replace` function and causes the `TypeError`).

### Input

```js
var input = `BEGIN:VCARD
VERSION:4.0
ADR;TYPE=home;LABEL="Test 42, Berlin":;;Test 42\, Berlin;;;;
END:VCARD
`;

var jCal = ICAL.parse(input);
console.dir(jCal);

var vcard = ICAL.stringify.component(jCal);
console.log(vcard);
```

### Actual result

```js
[
  "vcard",
  [
    ["version",{},"text","4.0"],
    ["adr",{"type":"home","label":["Test 42"," Berlin"]},"text",["","",["Test 42"," Berlin"],"","","",""]]],
    []
]

// Uncaught TypeError: t.replace is not a function
//     at Function.r._rfc6868Unescape (ical.js:1657)
//     at Function.r.property (ical.js:1493)
//     at Function.r.component (ical.js:1444)
```

### Expected result

```js
[
  "vcard",
  [
    ["version",{},"text","4.0"],
    ["adr",{"type":"home","label":"Test 42, Berlin"},"text",["","","Test 42, Berlin","","","",""]]],
    []
]

// BEGIN:VCARD
// VERSION:4.0
// ADR;TYPE=home;LABEL="Test 42, Berlin":;;Test 42\, Berlin;;;;
// END:VCARD
```

### PR DESCRIPTION
**Pull request by caugner**
Fixes #386.

### CODE REVIEW

**Comment by skjnldsv** [comment]
@kewisch @mschroeder? :)

**Review by skjnldsv — APPROVED** [review]

**Comment by RuralYak** [comment]
@caugner could you please update your branch from upstream and merge this since you have an appoval. Looks like everyone just sit and wait for anyone who will do that

**Comment by RuralYak** [comment]
@skjnldsv looks like @caugner Claas disappeared but this fix is important for Nextcloud project because it fixes major part of it

**Comment by skjnldsv** [comment]
@RuralYak this library is not part of our project.
Caugner did not disappeared, we're just waiting for the owners of the https://github.com/mozilla-comm/ical.js repository

**Comment by kewisch** [comment]
Hang in there, I'm working on the PR backlog!

**Comment by RuralYak** [comment]
@skjnldsv and how long it usually takes to get an attention from owners?

**Comment by skjnldsv** [comment]
> @skjnldsv and how long it usually takes to get an attention from owners?

Every project is different! ;)
People sometimes work on github and fixes are right away, while some owners are just volunteers and just don't have the time!; some libraries are abandoned, some are active! :)
Open source is how it is! While some outcome might not be ideal, we're all human and passionate over one thing: free code and common good! :cupid: 

> Good things come to those who wait

**Comment by RuralYak** [comment]
Is it somehow possible to get an attention to this PR? https://github.com/nextcloud/contacts/issues/1009 depends on it and they just sit and wait

**Comment by skjnldsv** [comment]
> Is it somehow possible to get an attention to this PR? [nextcloud/contacts#1009](https://github.com/nextcloud/contacts/issues/1009) depends on it and they just sit and wait

@kewisch just answered this pr and is the owner :)
(Feel free to hide our message as off topic to not clutter this pr Philipp)

**Comment by kewisch** [comment]
No worries, my fault for not taking care sooner! I'm trying to do a pr or two every few days depending on time.

**Comment by caugner** [comment]
@kewisch Same here, please let me know if you need me to resolve those conflicts by rebuilding the files.

**Comment by RuralYak** [comment]
@kewisch please let us know how we could help merge this

**Comment by kewisch** [comment]
I've rebased this and made some slight changes, let me know what you think. It seems to make sense to reset `mvdelim` and `multiValue` on each loop run, as in the next iteration there would be no reason to assume the value continues to be multi value.

@caugner let me know if you see any obvious downsides, if not I'll go ahead and merge.

**Comment by caugner** [comment]
@kewisch Thanks for the review, your change makes total sense. 👍

**Pull request merged**
