### PR TITLE
Fixes: startOfWeek and endOfWeek does not return dates

### LINKED ISSUE #125: Time: startOfWeek and endOfWeek does not return dates
I was a bit surprised that `startOfWeek` and `endOfWeek` does not return a date like `endOfMonth` and `startOfYear`. Is that on purpose? If not I would happily create a pull request for it.

### PR DESCRIPTION
**Pull request by sunesimonsen**
Fixes #125 

This pull request makes `startOfWeek` and `endOfWeek` return dates as `startOfMonth`, `endOfMonth`, `startOfYear` and `endOfYear` already does.

### CODE REVIEW

**Comment by kewisch** [comment]
Looks good. Could you add a second commit after calling `make package` ? This updates the browser build we have in the build/ folder.

**Comment by sunesimonsen** [comment]
Definitely - sorry for forgetting that.

**Comment by sunesimonsen** [comment]
Done, I just amended it and forced pushed to the pull request branch.

**Comment by kewisch** [comment]
Thanks! For the next pull request, go ahead and keep the browser build as a separate commit.

**Comment by sunesimonsen** [comment]
Oh - sorry. I'll remember that. I'm sure that it is not my last pull request.

**Pull request merged**
