### PR TITLE
README: add npm badge + installation step

### PR DESCRIPTION
**Pull request by odeke-em**
Added npm badge for easy information summary as well npm installation step.

### CODE REVIEW

**Comment by kewisch** [comment]
Thanks!

**Comment by kewisch** [comment]
Hm I've now looked at this, for some reason I assumed it would be a small badge like the "build passing" badge. Do you think you could send another pull request to use that kind of badge instead and put it in line with the build passing badge?

**Comment by odeke-em** [comment]
For sure, I can send one in about 2 hours as soon as I get home. Thank you for looking at it and for the initial merge.

**Comment by odeke-em** [comment]
@kewisch sorry for the late reply, got swamped with random things on getting home.
Fixed with PR https://github.com/mozilla-comm/ical.js/pull/146.
Thank you.

**Comment by kewisch** [comment]
I don't consider a day late reply :-) Thanks for taking care!

**Comment by odeke-em** [comment]
Thank you for the review and merge.

**Pull request merged**
