### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by lightsofapollo**
This PR lands some bug fixes and a major folder restructuring.
- restructures folders to follow a nodejs inspired convention.
- creates a top-level Makefile
- removes xpcom wrappers ( I can put them back I removed these because I probably broke them and the   tests are not yet hooked up to support them. I propose getting the xpcom tests setup next week and verifying that its working along the way by running the test suite vs xpcom)
- Adds new mocha/test-agent/chai based tests. You need nodejs to setup the test environment. I can make this easier by bundling all the code in the repo but it will add quite a bit of history. Its a trade off let me know what you think.
- Re-design top level api to only use `ICAL.parse` `ICAL.stringify`following the JSON's conventions.
- ICAL.icalcomponent objects can now be JSON.stringify'ed directly.
- blank lines no longer throw parser errors.
- fixes stack trace in parser errors in browser environments (we probably need a different solution in xpcom, I have some helpful stuff for this elsewhere).

### CODE REVIEW

**Comment by lightsofapollo** [comment]
@kewisch Sorry for this massive set of changes. I am going to land my forked code in caldav.js -> gaia for now but I fully expect to get everything in sync after the review.

**Comment by kewisch** [comment]
Aside from above comments r=philipp. Let me know when new commits are added so I can merge

**Comment by lightsofapollo** [comment]
@kewisch When you use new Error() vs Object.create it sets the stack of all future ParserErrors to that location (in Firefox). I _think_ If I switched it back but left the stack code in place (the try/catch in the constructor) that should still work though the other stack will stay around in the prototype...

Whats browsers do we wish to support? My mental model these days is ES5 (IE9+, Chrome, Safari, Mobile Safari, Chrome, NodeJS).

In CalDAV I am being more extreme and doing something like this for inheritance:

``` js

function MyThing() {}

MyThing.prototype = {
  // this is in all ES5 runtimes & is now part of ES6 spec
  __proto__: OtherClass.prototype
}; 

```

**Comment by lightsofapollo** [comment]
@kewisch Removed other top level methods from ICAL now there is only ICAL.parse & ICAL.stringify.

**Comment by kewisch** [comment]
Since IE8 still has around 18% market share (vs 12% for IE9), I think we 
should also support IE8. I guess if something like error stacks doesn't 
work there its ok, but lets try to make sure it doesn't fail hard. I 
haven't actually tested, but it looks like what you are doing for 
inheritance in the code example will at least not break IE8.

**Comment by lightsofapollo** [comment]
@kewisch OK, I removed the Object.create in favor of **proto** based inheritance. 
I think that address the last of the review comments.

**Pull request merged**
