### PR TITLE
Failing test

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
This new test fails, but it should succeed.

Duplicate of https://github.com/kewisch/ical.js/pull/537.

### CODE REVIEW

**Comment by kewisch** [comment]
Oops, I accidentally pushed this to main, let's hope it works:

https://github.com/kewisch/ical.js/commit/76ce13ac9ff0c12c3e105a0e71280126b516a55e

**Comment by kewisch** [comment]
Looks like it does! I'm going to close this PR again, your failing test is now included and #669 covers fixing it. Please do add more if you find them!

**Comment by dilyanpalauzov** [comment]
I think the test in https://github.com/kewisch/ical.js/pull/534 also fails, even if it should not.

**Comment by kewisch** [comment]
Could you provide a PR to add it to the known failures file?

**Comment by dilyanpalauzov** [comment]
No

**Comment by kewisch** [comment]
Alright, we'll wait until this lands in someone's focus then. Thanks for the mention!

**Pull request closed without merging**
