### PR TITLE
Failing test

### PR DESCRIPTION
**Pull request by dilyanpalauzov**
This new test fails, but it should succeed.

### CODE REVIEW

**Comment by kewisch** [comment]
Strange, the tests seem to work on my machine, and your PR fails in CI. Do you know what the expected behavior should be, e.g. do we need to change the code?

**Comment by dilyanpalauzov** [comment]
The expected behaviour is that the test does not fail.

**Comment by kewisch** [comment]
Ah, understood now, thank you.

**Comment by kewisch** [comment]
Fixed by #536, thank you!

**Comment by dilyanpalauzov** [comment]
I rebased this test on the main branch.  It is still failing:

```
      + expected - actual                                                                                                               
                                                                                                                                        
           ]                                                                                                                            
           [                                                                                                                            
             "attendee"                                                                                                                 
             {
      -        "cn": "Z;"
      +        "cn": "Z\\;"
             }
             "cal-address"
             "mailto:z@example.org"
           ]
       
```

**Comment by kewisch** [comment]
Ah strange, I tested on my machine and it seemed to be working. Will take another look.

**Comment by dilyanpalauzov** [comment]
Can this be reopened?

**Comment by kewisch** [comment]
I'm getting a github error and can't reopen it. Can you move this to a new branch? I think it might make sense to either keep the failing test code in an issue, or submit a PR with a patch. Otherwise we'll have the PR open until someone comes around to fixing it and I'd eventually like to get to 0 PRs.

**Comment by dilyanpalauzov** [comment]
Did you got eventually this test failing on your system?

Can you create some mechanism for tests, which are not supposed to fail, but currently fail (expected failures)?

**Comment by kewisch** [comment]
Have not tried, sorry. I have some vacation this week and can take a look. I had also thought about an expected failure system, I didn't see an obvious way when I skimmed last time.

**Pull request closed without merging**
